### PR TITLE
add phpstan timeout option

### PR DESCRIPTION
**Pull request by npo-mmenke**
adds an option to configure the phpstan timeout, see https://github.com/TomasVotruba/phpstan-bodyscan/issues/28

I'm having issues building this locally though... I'm getting the following errors on full-tool-build.sh:

`[ERROR] Could not process "/var/www/html/vendor/symfony/console/Command/LockableTrait.php" file, due to:
         "System error: "Scope not available on "PhpParser\Node\Stmt\Expression" node, but is required by a
         refactorWithScope() method of "Rector\DowngradePhp80\Rector\Expression\DowngradeMatchToSwitchRector" rule. Fix
         scope refresh on changed nodes first"
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On line: 25

 [ERROR] Could not process "/var/www/html/vendor/symfony/service-contracts/ServiceSubscriberTrait.php" file, due to:
         "System error: "Scope not available on "PhpParser\Node\Stmt\Expression" node, but is required by a
         refactorWithScope() method of "Rector\DowngradePhp80\Rector\Expression\DowngradeMatchToSwitchRector" rule. Fix
         scope refresh on changed nodes first"
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On line: 25

 [ERROR] Could not process "/var/www/html/vendor/symfony/service-contracts/ServiceLocatorTrait.php" file, due to:
         "System error: "Scope not available on "PhpParser\Node\Expr\Array_" node, but is required by a
         refactorWithScope() method of "Rector\DowngradePhp81\Rector\Array_\DowngradeArraySpreadStringKeyRector" rule.
         Fix scope refresh on changed nodes first"
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On line: 25

 [ERROR] Could not process "vendor/symfony/console/Tester/ApplicationTester.php" file, due to:
         "Analyze error: "Class PHPStanBodyscan202407\Symfony\Component\Console\Tester\ApplicationTester was not found
         while trying to analyse it - discovering symbols is probably not configured properly.". Include your files in
         "$rectorConfig->autoloadPaths([...]);" or "$rectorConfig->bootstrapFiles([...]);" in "rector.php" config.
         See https://github.com/rectorphp/rector#configuration".

 [ERROR] Could not process "vendor/symfony/console/Tester/CommandTester.php" file, due to:
         "Analyze error: "Class PHPStanBodyscan202407\Symfony\Component\Console\Tester\CommandTester was not found while
         trying to analyse it - discovering symbols is probably not configured properly.". Include your files in
         "$rectorConfig->autoloadPaths([...]);" or "$rectorConfig->bootstrapFiles([...]);" in "rector.php" config.
         See https://github.com/rectorphp/rector#configuration".`

On executing the binary the following error occurs:

PHP Fatal error:  Uncaught Error: Class "PHPStanBodyscan202407\Illuminate\Container\Container" not found in /var/www/html/src/DependencyInjection/ContainerFactory.php:17

Any idea?

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Thanks :+1: 

Local build is not required, as this script is probably outdated and we only use CI to do the build.
What is required is passing CI.

**Comment by npo-mmenke** [comment]
not sure how this works, do I need to do something to trigger the ci again?

**Comment by TomasVotruba** [comment]
@npo-mmenke Its Github's default once you contribute a new repository first time. Not very helpful though https://github.com/orgs/community/discussions/14334

I have to basically confirm everytime you push a commit. Once we merge something, you'll be verified as "known user" and CI will run automatically :)

**Comment by npo-mmenke** [comment]
anything else you need from me here?

**Review by TomasVotruba — APPROVED** [review]

**Comment by TomasVotruba** [comment]
Looks good, thanks 👍

**Pull request merged**
